//! Errors for when codec goes wrong.

#[cfg(feature = "alloc")]
use alloc::boxed::Box;
use core::{convert::Infallible, fmt};
#[cfg(feature = "defmt-1")]
use defmt::{Debug2Format, Display2Format, Format};

use crate::io;

/// Alias for a [`Result`](core::result::Result) with the error type [`Error`].
pub type Result<T> = core::result::Result<T, Error>;

/// Category of codec error.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
#[non_exhaustive]
#[allow(missing_docs)]
pub enum ErrorKind {
    Io(io::ErrorKind),
    #[cfg(feature = "alloc")]
    FromUtf8,
    #[cfg(feature = "alloc")]
    Nul,
    TryFromInt,
    Borrow,
    Discriminant,
    TagConvert,
    #[cfg(feature = "std")]
    Poison,
    Underrun,
    EncodeSkipped,
    Magic,
    #[cfg(feature = "alloc")]
    TryReserve,
    Assert,
    Other,
}

/// Codec error.
#[derive(Debug)]
pub struct Error {
    inner: ErrorCause,
}

impl Error {
    #[doc(hidden)]
    #[inline]
    #[must_use]
    pub const fn from_inner(inner: ErrorCause) -> Self {
        Self { inner }
    }

    /// Create a new error from a static string.
    #[inline]
    #[must_use]
    pub const fn msg(msg: &'static str) -> Self {
        Self {
            inner: ErrorCause::Other(msg),
        }
    }

    /// Create a new error from an arbitrary error.
    #[inline]
    #[must_use]
    #[cfg(feature = "alloc")]
    pub fn custom<E>(inner: E) -> Self
    where
        E: Into<Box<dyn core::error::Error + Send + Sync>>,
    {
        Self {
            inner: ErrorCause::Boxed(inner.into()),
        }
    }

    /// Returns the corresponding [`ErrorKind`] for this error.
    #[inline]
    #[must_use]
    pub fn kind(&self) -> ErrorKind {
        self.inner.kind()
    }
}

impl From<ErrorCause> for Error {
    #[inline]
    fn from(inner: ErrorCause) -> Self {
        Self { inner }
    }
}

#[derive(Debug)]
#[doc(hidden)]
pub enum ErrorCause {
    Io(io::Error),
    #[cfg(feature = "alloc")]
    FromUtf8(alloc::string::FromUtf8Error),
    #[cfg(feature = "alloc")]
    Nul(alloc::ffi::NulError),
    TryFromInt(core::num::TryFromIntError),
    Borrow(core::cell::BorrowError),
    Discriminant,
    TagConvert,
    #[cfg(feature = "std")]
    Poison,
    Underrun {
        read_bits: u64,
        available_bits: u64,
    },
    EncodeSkipped,
    Magic,
    #[cfg(feature = "alloc")]
    TryReserve(alloc::collections::TryReserveError),
    Assert(&'static str),
    #[cfg(feature = "alloc")]
    /// A catch-all for errors generated by user code
    Boxed(Box<dyn core::error::Error + Send + Sync>),
    /// A catch-all for error generated by user code, with a static message
    Other(&'static str),
}

impl ErrorCause {
    pub(crate) fn kind(&self) -> ErrorKind {
        match self {
            Self::Io(error) => ErrorKind::Io(error.kind()),
            #[cfg(feature = "alloc")]
            Self::FromUtf8(_) => ErrorKind::FromUtf8,
            #[cfg(feature = "alloc")]
            Self::Nul(_) => ErrorKind::Nul,
            Self::TryFromInt(_) => ErrorKind::TryFromInt,
            Self::Borrow(_) => ErrorKind::Borrow,
            Self::Discriminant => ErrorKind::Discriminant,
            Self::TagConvert => ErrorKind::TagConvert,
            #[cfg(feature = "std")]
            Self::Poison => ErrorKind::Poison,
            Self::Underrun { .. } => ErrorKind::Underrun,
            Self::EncodeSkipped => ErrorKind::EncodeSkipped,
            Self::Magic => ErrorKind::Magic,
            #[cfg(feature = "alloc")]
            Self::TryReserve(_) => ErrorKind::TryReserve,
            Self::Assert(_) => ErrorKind::Assert,
            #[cfg(feature = "alloc")]
            Self::Boxed(_) => ErrorKind::Other,
            Self::Other(_) => ErrorKind::Other,
        }
    }
}

impl fmt::Display for Error {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.inner.fmt(f)
    }
}

impl fmt::Display for ErrorCause {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Io(e) => e.fmt(f),
            #[cfg(feature = "alloc")]
            Self::FromUtf8(e) => e.fmt(f),
            #[cfg(feature = "alloc")]
            Self::Nul(e) => e.fmt(f),
            Self::TryFromInt(e) => e.fmt(f),
            Self::Borrow(e) => e.fmt(f),
            Self::Discriminant => "unknown enum discriminant".fmt(f),
            Self::TagConvert => "failed to convert tag".fmt(f),
            #[cfg(feature = "std")]
            Self::Poison => "poisoned lock".fmt(f),
            Self::Magic => "magic mismatch".fmt(f),
            Self::Underrun {
                read_bits: read,
                available_bits: available,
            } => write!(f, "buffer underrun: read {read} of {available} bits"),
            Self::EncodeSkipped => "attempted to encode skipped enum variant".fmt(f),
            #[cfg(feature = "alloc")]
            Self::TryReserve(e) => e.fmt(f),
            Self::Assert(e) => write!(f, "assertion failed: {e}"),
            #[cfg(feature = "alloc")]
            Self::Boxed(e) => e.fmt(f),
            Self::Other(e) => write!(f, "other: {e}"),
        }
    }
}

#[cfg(feature = "defmt-1")]
impl Format for Error {
    fn format(&self, fmt: defmt::Formatter) {
        self.inner.format(fmt);
    }
}

#[cfg(feature = "defmt-1")]
impl Format for ErrorCause {
    fn format(&self, fmt: defmt::Formatter) {
        match self {
            Self::Io(e) => Display2Format(e).format(fmt),
            #[cfg(feature = "alloc")]
            Self::FromUtf8(e) => Display2Format(e).format(fmt),
            #[cfg(feature = "alloc")]
            Self::Nul(e) => Display2Format(e).format(fmt),
            Self::TryFromInt(e) => e.format(fmt),
            Self::Borrow(e) => e.format(fmt),
            Self::Discriminant => "unknown enum discriminant".format(fmt),
            Self::TagConvert => "failed to convert tag".format(fmt),
            #[cfg(feature = "std")]
            Self::Poison => "poisoned lock".format(fmt),
            Self::Magic => "magic mismatch".format(fmt),
            Self::Underrun {
                read_bits: read,
                available_bits: available,
            } => defmt::write!(fmt, "buffer underrun: read {} of {} bits", read, available),
            Self::EncodeSkipped => "attempted to encode skipped enum variant".format(fmt),
            #[cfg(feature = "alloc")]
            Self::TryReserve(e) => Display2Format(e).format(fmt),
            Self::Assert(e) => defmt::write!(fmt, "assertion failed: {}", e),
            #[cfg(feature = "alloc")]
            Self::Boxed(e) => Display2Format(e).format(fmt),
            Self::Other(e) => defmt::write!(fmt, "other: {}", e),
        }
    }
}

#[cfg(feature = "defmt-1")]
impl Format for ErrorKind {
    fn format(&self, fmt: defmt::Formatter) {
        match self {
            Self::Io(kind) => Debug2Format(kind).format(fmt),
            #[cfg(feature = "alloc")]
            Self::FromUtf8 => "from utf8".format(fmt),
            #[cfg(feature = "alloc")]
            Self::Nul => "nul".format(fmt),
            Self::TryFromInt => "try from int".format(fmt),
            Self::Borrow => "borrow".format(fmt),
            Self::Discriminant => "discriminant".format(fmt),
            Self::TagConvert => "tag convert".format(fmt),
            #[cfg(feature = "std")]
            Self::Poison => "posion".format(fmt),
            Self::Underrun => "underrun".format(fmt),
            Self::EncodeSkipped => "encode skipped".format(fmt),
            Self::Magic => "magic".format(fmt),
            #[cfg(feature = "alloc")]
            Self::TryReserve => "try reserve".format(fmt),
            Self::Assert => "assert".format(fmt),
            Self::Other => "other".format(fmt),
        }
    }
}

impl From<io::Error> for Error {
    #[inline]
    fn from(value: io::Error) -> Self {
        Self {
            inner: ErrorCause::Io(value),
        }
    }
}

#[cfg(feature = "alloc")]
impl From<alloc::string::FromUtf8Error> for Error {
    #[inline]
    fn from(value: alloc::string::FromUtf8Error) -> Self {
        Self {
            inner: ErrorCause::FromUtf8(value),
        }
    }
}

#[cfg(feature = "alloc")]
impl From<alloc::ffi::NulError> for Error {
    #[inline]
    fn from(value: alloc::ffi::NulError) -> Self {
        Self {
            inner: ErrorCause::Nul(value),
        }
    }
}

impl From<core::num::TryFromIntError> for Error {
    #[inline]
    fn from(value: core::num::TryFromIntError) -> Self {
        Self {
            inner: ErrorCause::TryFromInt(value),
        }
    }
}

impl From<core::cell::BorrowError> for Error {
    #[inline]
    fn from(value: core::cell::BorrowError) -> Self {
        Self {
            inner: ErrorCause::Borrow(value),
        }
    }
}

impl From<Infallible> for Error {
    #[inline]
    fn from(_: Infallible) -> Self {
        unreachable!()
    }
}

#[cfg(feature = "std")]
impl<T> From<std::sync::PoisonError<T>> for Error {
    fn from(_: std::sync::PoisonError<T>) -> Self {
        Self {
            inner: ErrorCause::Poison,
        }
    }
}

#[cfg(feature = "alloc")]
impl From<alloc::collections::TryReserveError> for Error {
    #[inline]
    fn from(value: alloc::collections::TryReserveError) -> Self {
        Self {
            inner: ErrorCause::TryReserve(value),
        }
    }
}

impl core::error::Error for Error {}

#[cfg(test)]
mod tests {
    use super::*;

    #[allow(unused)]
    trait IsSizedSendSync: Sized + Send + Sync {}

    impl IsSizedSendSync for Error {}
}
